### ISSUE TITLE
Internal server error on first page of study creation wizard

### ISSUE THREAD

**Issue by mhmoed** [PhenotypeFoundation/PhenotypeDatabse#114]
I'm trying to complete the create study wizard, but the wizard hangs (i.e. nothing happens) after clicking "next" on the first page. On inspection of the application logs it seems this is caused by an internal server error (the AJAX request returns an error page detailing the same error as well).

Before starting the wizard I created a default study template. The Template, Title, Description, Code and Start Date fields are all filled out uniquely, and I've added one contact, one reader and one writer. After clicking "next", nothing happens, and the application log shows the following:
```
2015-04-16 18:38:33,847 [http-8080-1] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /studyWizard/pages
Cannot get property 'ncboId' on null object. Stacktrace follows:
org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'subjects' of flow 'studyWizard/pages'
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Exception occurred rendering view org.codehaus.groovy.grails.web.servlet.view.GroovyPageView: unnamed; URL [//studyWizard/pages/_subjects.gsp]
	... 1 more
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Cannot get property 'ncboId' on null object
	... 1 more
Caused by: java.lang.NullPointerException: Cannot get property 'ncboId' on null object
	at gsp_gscf_studyWizard_pages_subjects_gsp$_run_closure2.doCall(gsp_gscf_studyWizard_pages_subjects_gsp.groovy:30)
	at gsp_gscf_studyWizard_pages_subjects_gsp.run(gsp_gscf_studyWizard_pages_subjects_gsp.groovy:30)
	... 1 more
```
Is something wrong in my configuration perhaps? I can upload the GSCF .properties file if needed.

**Comment by michaelvanvliet** [comment]
Did you provide an api-key on line 45 of https://github.com/PhenotypeFoundation/GSCF/blob/master/grails-app/conf/default.properties ? You can request on via https://bioportal.bioontology.org/account

**Comment by mhmoed** [comment]
I've added my API key to the configuration file. Based on the logs it looks like GSCF can connect to BioPortal. However, inserting ontology data into the database seems to fail, and the application refuses to start: 
```
...
2015-04-17 16:15:33,633 [main] WARN  util.JDBCExceptionReporter  - SQL Error: 0, SQLState: 23502
2015-04-17 16:15:33,634 [main] ERROR util.JDBCExceptionReporter  - Batch entry 0 insert into ontology (version, acronym, date_created, last_updated, name, url, id) values ('0', 'NCBITAXON', '2015-04-17 16:15:33.612000 +02:00:00', '2015-04-17 16:15:33.612000 +02:00:00', 'National Center for Biotechnology Information (NCBI) Organismal Classification', 'http://data.bioontology.org/ontologies/NCBITAXON', '12') was aborted.  Call getNextException to see the cause.
2015-04-17 16:15:33,634 [main] WARN  util.JDBCExceptionReporter  - SQL Error: 0, SQLState: 23502
2015-04-17 16:15:33,635 [main] ERROR util.JDBCExceptionReporter  - ERROR: null value in column "description" violates not-null constraint
  Detail: Failing row contains (12, 0, 2015-04-17 16:15:33.612, null, 2015-04-17 16:15:33.612, National Center for Biotechnology Information (NCBI) Organismal ..., null, null, http://data.bioontology.org/ontologies/NCBITAXON, null, NCBITAXON).
2015-04-17 16:15:33,640 [main] ERROR events.PatchedDefaultFlushEventListener  - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.dbnp.gdt.Ontology.getOrCreateOntology(Ontology.groovy:63)
	at BootStrap$_closure1.doCall(BootStrap.groovy:91)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into ontology (version, acronym, date_created, last_updated, name, url, id) values ('0', 'NCBITAXON', '2015-04-17 16:15:33.612000 +02:00:00', '2015-04-17 16:15:33.612000 +02:00:00', 'National Center for Biotechnology Information (NCBI) Organismal Classification', 'http://data.bioontology.org/ontologies/NCBITAXON', '12') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2598)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)
	at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	... 5 more
2015-04-17 16:15:33,646 [main] ERROR context.GrailsContextLoader  - Error initializing the application: Could not execute JDBC batch update; SQL [insert into ontology (version, acronym, date_created, last_updated, name, url, id) values (?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into ontology (version, acronym, date_created, last_updated, name, url, id) values (?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
...
```
The complete log can be found [here](https://gist.github.com/mhmoed/218e67611490e8c0ae1c).

As far as I can tell, the GSCF database user has all the correct permissions for its database:
```
mhmoed@mlpd-db01 ~tomcat6[16:26:46] 
> $ sudo su - postgres                                                                                                                                                                                                                                  
[sudo] password for mhmoed: 
postgres@mlpd-db01:~$ psql -c "\l"
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 gscf-www  | gscfuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/gscfuser         +
           |          |          |             |             | gscfuser=CTc/gscfuser
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)
```

**Comment by roberthorlings** [comment]
I think this issue is due to changes in the Bioportal api, somewhere in 2014. GSCF (to be more specific: the [GDT plugin](https://github.com/PhenotypeFoundation/GDT/)) has been updated to handle the new API setup. 

However, looking at your log messages, it seems that you are using a version of the application that does not support the new API (it is referring to the description property of an Ontology object, which has been removed in [commit 1892f284](https://github.com/PhenotypeFoundation/GDT/commit/1892f28425e25fef79e80a4aa1e2d675d42ea104#diff-9f39cc4d75112d919d22c26663c665e8). That would be the case if you are using a prebuilt war file or compiled your war file from the release branch. In that case, the application has a version number in the 0.9.0.x series. You can check the version number as an administrator by going to Admin -> Application info. 

GSCF versions > 0.9.2.3 should work fine. You could create your own war file from the master branch manually, which would solve this issue anyhow.

**Comment by mhmoed** [comment]
It appears I was using an older version. Upgrading to the latest version (0.9.5.2) solves the issue. Thanks!
